//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT.BusinessObjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APTRate_Master
    {
        public decimal RATE_0_23 { get; set; }
        public decimal RATE_24_29 { get; set; }
        public decimal RATE_30_39 { get; set; }
        public decimal RATE_40_47 { get; set; }
        public decimal RATE_48_57 { get; set; }
        public decimal RATE_58_65 { get; set; }
        public decimal RATE_66_75 { get; set; }
        public decimal RATE_76_99 { get; set; }
        public decimal RATE_100_149 { get; set; }
        public decimal RATE_150_199 { get; set; }
        public decimal RATE_200_299 { get; set; }
        public decimal RATE_300_More { get; set; }
        public decimal FUEL_SURCHARGE { get; set; }
        public decimal CHASSIS_FEE { get; set; }
        public decimal ADDITIONAL { get; set; }
    }
}
