//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT.BusinessObjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legs_RateQuote
    {
        public int Id { get; set; }
        public Nullable<int> RateQuoteId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string OneWayMiles { get; set; }
        public Nullable<decimal> RoundTrip { get; set; }
        public Nullable<decimal> BaseFare { get; set; }
        public Nullable<decimal> FuelSurcharge { get; set; }
        public Nullable<decimal> ChasisFees { get; set; }
        public Nullable<decimal> AdditionalFare { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PayType { get; set; }
        public Nullable<decimal> LineHaulAmount { get; set; }
        public string Distance { get; set; }
        public string TravelTime { get; set; }
        public Nullable<decimal> OneWayBase { get; set; }
        public string GUID { get; set; }
    }
}
