//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT.BusinessObjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateQuote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RateQuote()
        {
            this.RQLegs = new HashSet<RQLeg>();
            this.RQAdditionalItems = new HashSet<RQAdditionalItem>();
        }
    
        public int RateQuoteId { get; set; }
        public Nullable<int> BillTo { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<bool> RoundTrip { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UppdatedDate { get; set; }
        public string GUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RQLeg> RQLegs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RQAdditionalItem> RQAdditionalItems { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
