//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT.BusinessObjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQLeg
    {
        public int RQLegId { get; set; }
        public Nullable<int> RateQuoteId { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string OneWayMiles { get; set; }
        public string TravelTime { get; set; }
        public Nullable<decimal> LineHaul { get; set; }
        public Nullable<decimal> FuelSurcharge { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool ToDispatch { get; set; }
        public Nullable<bool> Converted { get; set; }
        public string GUID { get; set; }
        public string RQFrom { get; set; }
    
        public virtual RateQuote RateQuote { get; set; }
    }
}
